import { createSebastianApplication } from '../application/SebastianApplication.js';

export const core = createSebastianApplication();

export { createCore } from './core.js';
export * from './CorePipelineIntegrationErrors.js';
export * from './CorePipelineBootstrap.js';
export * from './CorePipelineBootstrapErrors.js';
export * from './CoreOperationalRuntimeBootstrap.js';
export * from './CoreOperationalRuntimeBootstrapErrors.js';
export * from './config.js';
export * from './logger.js';
export * from './types.js';
export * from './events/EventBus.js';
export * from './events/EventTypes.js';
export * from './container/index.js';
export * from './lifecycle/index.js';
export * from './plugins/index.js';
export * from './errors/index.js';
export * from './health/index.js';
export * from './config/index.js';
export * from './agent/index.js';
export * from './tool/index.js';
export * from './memory/index.js';
export * from './model/index.js';
export * from './development/index.js';
export * from './cognition/index.js';
export * from './conversation/index.js';
export * from './context/index.js';
export * from './command/index.js';
export * from './capability/index.js';
export * from './project/index.js';
export * from '../application/index.js';
