export enum ErrorCategory {
  SYSTEM = 'SYSTEM',
  PLUGIN = 'PLUGIN',
  LIFECYCLE = 'LIFECYCLE',
  CONTAINER = 'CONTAINER',
  EVENTBUS = 'EVENTBUS',
  VALIDATION = 'VALIDATION',
  UNKNOWN = 'UNKNOWN',
}
